version: '2'
services:
    gateway-app:
        image: gateway
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://gateway-postgresql:5432/gateway
            - JHIPSTER_SLEEP=30
            - JHIPSTER_REGISTRY_PASSWORD=admin
        ports:
            - 8080:8080
    gateway-postgresql:
        image: postgres:9.6.5
        environment:
            - POSTGRES_USER=gateway
            - POSTGRES_PASSWORD=

    market-app:
        image: market
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATA_MONGODB_URI=mongodb://market-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=market
            - JHIPSTER_SLEEP=90
            - JHIPSTER_REGISTRY_PASSWORD=admin
    market-mongodb:
        image: mongo:3.4.8

    portfolio-app:
        image: portfolio
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://portfolio-postgresql:5432/portfolio
            - JHIPSTER_SLEEP=90
            - JHIPSTER_REGISTRY_PASSWORD=admin
    portfolio-postgresql:
        image: postgres:9.6.5
        environment:
            - POSTGRES_USER=portfolio
            - POSTGRES_PASSWORD=

    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
